name: Terraform Lint & Validate

on:
  pull_request:
    paths:
      - 'infrastructure/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: infrastructure/
        run: terraform init -backend=false

      - name: Terraform Format Check
        working-directory: infrastructure/
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: infrastructure/
        run: terraform validate
